apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: glusterfs-storage
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/glusterfs
  creationTimestamp: '2018-03-04T18:12:42Z'
  name: vol1-openhab
  namespace: openhab
  resourceVersion: '3360072'
  selfLink: /api/v1/namespaces/openhab/persistentvolumeclaims/vol1-openhab
  uid: a15bd300-1fd7-11e8-8034-02163e6303d0
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
