apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
  creationTimestamp: '2018-03-04T20:33:13Z'
  labels:
    app: openhab
  name: openhab
  namespace: openhab
  resourceVersion: '3365432'
  selfLink: /api/v1/namespaces/openhab/services/openhab
  uid: 42c2bb36-1feb-11e8-8034-02163e6303d0
spec:
  clusterIP: 172.30.65.116
  ports:
    - name: 5007-tcp
      port: 5007
      protocol: TCP
      targetPort: 5007
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8101-tcp
      port: 8101
      protocol: TCP
      targetPort: 8101
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
  selector:
    deploymentconfig: openhab
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
